#include "data.h"
std::vector<question> data = {
    {"What is the capital of France?", {"Berlin", "Madrid", "Paris", "Rome"}, 2},
    {"Which planet is known as the Red Planet?", {"Earth", "Mars", "Jupiter", "Saturn"}, 1},
    {"What is the result of 3 + 4 * 2?", {"14", "11", "10", "9"}, 1},
    {"Which language is used for Android development?", {"Python", "Kotlin", "Swift", "Ruby"}, 1},
    {"Who painted the Mona Lisa?", {"Vincent Van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"}, 2},
    {"What is the largest ocean on Earth?", {"Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"}, 3},
    {"In which year did the Titanic sink?", {"1905", "1912", "1918", "1923"}, 1},
    {"What is the chemical symbol for gold?", {"Au", "Ag", "Gd", "Go"}, 0},
    {"Which country is known as the Land of the Rising Sun?", {"China", "Japan", "Thailand", "South Korea"}, 1},
    {"Who wrote 'Romeo and Juliet'?", {"Charles Dickens", "Mark Twain", "William Shakespeare", "Jane Austen"}, 2},
    {"What is the hardest natural substance on Earth?", {"Gold", "Iron", "Diamond", "Platinum"}, 2},
    {"Which planet is closest to the sun?", {"Venus", "Earth", "Mercury", "Mars"}, 2},
    {"What is the smallest prime number?", {"0", "1", "2", "3"}, 2},
    {"Who was the first President of the United States?", {"Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"}, 2},
    {"What is the largest mammal in the world?", {"Elephant", "Blue Whale", "Giraffe", "Great White Shark"}, 1},
    {"Which element has the atomic number 1?", {"Oxygen", "Hydrogen", "Carbon", "Helium"}, 1},
    {"In which continent is the Sahara Desert located?", {"Asia", "Africa", "Australia", "South America"}, 1},
    {"What is the main ingredient in guacamole?", {"Tomato", "Avocado", "Cucumber", "Pepper"}, 1},
    {"Which planet has the most moons?", {"Earth", "Mars", "Jupiter", "Saturn"}, 2},
    {"Who discovered penicillin?", {"Marie Curie", "Alexander Fleming", "Isaac Newton", "Albert Einstein"}, 1},
    {"What is the capital of Australia?", {"Sydney", "Melbourne", "Canberra", "Brisbane"}, 2},
    {"Which gas do plants absorb from the atmosphere?", {"Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"}, 2},
    {"Who is known as the 'Father of Computers'?", {"Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"}, 1},
    {"What is the longest river in the world?", {"Amazon River", "Nile River", "Yangtze River", "Mississippi River"}, 1},
    {"Which language has the most native speakers?", {"English", "Spanish", "Mandarin Chinese", "Hindi"}, 2},
    {"What is the square root of 64?", {"6", "7", "8", "9"}, 2},
    {"Who painted the ceiling of the Sistine Chapel?", {"Leonardo da Vinci", "Vincent Van Gogh", "Michelangelo", "Raphael"}, 2},
    {"Which country hosted the 2016 Summer Olympics?", {"China", "Brazil", "UK", "Russia"}, 1},
    {"What is the chemical formula for water?", {"H2O", "CO2", "O2", "H2SO4"}, 0},
    {"Who wrote 'To Kill a Mockingbird'?", {"Harper Lee", "Mark Twain", "Ernest Hemingway", "F. Scott Fitzgerald"}, 0}};
